package com.epam.recreation_module.model.enums;

public enum Permission {

    ADD_ROLE,
    VIEW_ROLE,
    EDIT_ROLE,
    DELETE_ROLE,
    ADD_RECREATION,
    EDIT_RECREATION,
    DELETE_RECREATION,

    ADD_EVENT,
    EDIT_EVENT,
    DELETE_EVENT,
    ADD_USERS,
    EDIT_USERS,
    VIEW_USERS,
    DELETE_USERS,
    ADD_PHOTO,
    EDIT_PHOTO,
    DELETE_PHOTO,
    EDIT_COMMENT,
    DELETE_COMMENT,

    ADD_COMMENT,
    EDIT_MY_COMMENT,
    DELETE_MY_COMMENT,
    DELETE_MY_ACCOUNT,
    EDIT_MY_ACCOUNT
}
